server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: r2dbc:h2:mem:locationsDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:
  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
application:
  championschip:
    error:
      message:
        "7002": "lo sentimos, no hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente."
        "7000": "tu tiempo de conexión ha expirado. Por tu seguridad debes ingresar nuevamente."
        "7003": "No se tiene un resultado de la consulta para precios"
        "7004": "Los parametros de entrada son incorrectos"